package at.sti_innsbruck.tourpackclient.logic.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "THING".
 */
public class Thing {

    /** Not-null value. */
    private String thing_id;
    private String content;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Thing() {
    }

    public Thing(String thing_id) {
        this.thing_id = thing_id;
    }

    public Thing(String thing_id, String content) {
        this.thing_id = thing_id;
        this.content = content;
    }

    /** Not-null value. */
    public String getThing_id() {
        return thing_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setThing_id(String thing_id) {
        this.thing_id = thing_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
